See more updates
More live coverage: Markets
But with months of misinformation, politicization and downright confusion on just how to wear masks and which are best , many experts wonder: Are these futuristic creations credible? (To be clear, masks are very effective and save lives . People who don’t wear masks put everyone else at risk.)
Laurie Herzlin, 55, purchased two BioVyzrs, “to get back out into the world again as I have been in isolation for 203 days now.” She is immunocompromised and had planned to wear the face shield on a flight from her home in Florida to visit her daughter in Toronto.
“Yes, people will stare. They might even take pictures and post them on social media. But I would be OK with that,” Ms. Herzlin said. “I just want to stay healthy.”
After multiple emails and phone calls with Air Canada, providing them with photos of the BioVyzrs, which they requested, the airline refused to let her wear it on the plane. “Air Canada finally came back with a generic response that cited ‘safety concerns,’” she said.
A doctor in the airline’s medical department told her the BioVyzr “does not meet the description of permitted safety masks,” a reasoning Ms. Herzlin called “reckless.” (Air Canada declined to comment on the incident but said its mask policy follows the Canadian government’s regulations.)
Mr. Johnson said that between all his connecting flights en route to Alaska, only one T.S.A. agent made him take off his Air visor. “I said to him, ‘You’re asking me to take my mask off, but you’re letting everyone else keep their mask on,’” he recalled. “He had to tell somebody to take a mask off in a pandemic.” Once onboard, the Alaska Airlines crew was in awe: “The pilot said ‘I need one of those, how do I get one?’ The flight attendants thought it was the coolest thing.”
Image
The Air, which features built-in HEPA filters, four hours of power on a lithium battery and a removable washable fabric.Credit...MicroClimate
Are these masks more effective than normal masks?
Short answer is: No. Added eye protection, such as glasses or a visor, may be beneficial , according to a September study of 276 Covid-19 cases in a Chinese hospital in Suizhou. While such a small study group means it’s too early to draw conclusions, any barrier to touching our faces is positive.
But what about airflow — and just how airtight are they?
“For any mask or fancy filter, one thing we need to keep in mind is how well they fit, tightly, to the face,” said Chenyu Sun, an internist at Saint Joseph Hospital in Chicago who recently co-authored a study on face mask efficacy .
Dr. Sun said health care workers often get specially fitted for N95 masks, and the one-size-fits-all approach of retailers is troubling. So is the lack of guidance for proper use.
“Inside out, upside down, probably even less people know how to take masks off properly without contamination. This also applies to these devices,” said Dr. Sun, who added that sporting doomsday gear may have unintended psychological consequences. “Will the general public really accept these? Now, even for regular masks, there is a lot of debate.”
“People double-take, but I think Canada is very polite so nobody stares too long,” said Mr. Al-Qasi, who wears the BioVyzr around downtown Toronto, where the company is based.
Raina MacIntyre, the head of the Kirby Institute’s biosecurity research program at the University of New South Wales and the lead author on a recent face mask review , warns that if these masks don’t “provide a perfect seal on all contact surfaces, unfiltered air will flow preferentially through the gaps. HEPA filters are good for filtering pathogens, but these devices need to be tested for fit and filtration.”
She added: “The reason for needing a perfect seal is to force the air through the filter.”
Real efficacy, she said, means approval by the F.D.A. and the National Institute for Occupational Safety and Health , the agency that regulates this form of powered air respirator. “The virus is present in aerosols, so such a device will not be protective.”
The makers of the iSphere and the Air say they have no plans to test with either agency. Mr. Al-Qaysi said BioVyzr’s first model was not approved by an outside body, but that the company is “working to make sure future models are NIOSH approved.”
Yena Young, a creator of the iSphere who goes by the alter ego “Ms. Bubble,” calls her work more art than innovation. “iSphere has no medical evidence and we do not think that it is better than N95 masks,” she said. “But surely it opens up discussions about our perspectives, confusion from the lack of scientific knowledge, misunderstanding in greeting gestures, fear about covering faces, fear of others, the need of a transparent identity.”
David R. Hall, the chairman of Microclimate, which makes the Air, said the company is “still doing tests to verify our thesis that sealing at the neck is better than on the face.”
“The question of mask efficacy is a difficult one and very much dependent on the mask design and materials,” said Martin Fischer , a Duke University chemist. “I am not aware of any studies comparing HEPA-filtration masks and conventional cloth masks.”
While masks play a role in communication and expression , eye-popping products create false security, said Dr. Sun, who emphasizes continued need for affordable P.P.E., distancing and basic hygiene.
“A simple cloth covering, surgical or cloth mask, will be more than adequate for most people,” said Peter Chin-Hong, an infectious disease specialist at the University of California, San Francisco .
Beyond wild stares, futuristic masks “offer no further advantage,” he said. “There is absolutely no peer-reviewed literature or regulatory organization who has rigorously reviewed these data and certified it for occupational P.P.E.”
There is also new evidence that plastic coverings may not be as good as advertised. In late September, Japanese researchers reported that face masks provide effective protection and that nonwoven fabric masks block the most droplets from a cough. Plastic face shields are not very effective at protecting others, they found; they may protect a wearer against droplets from others, but not the other way around.
Dr. Chin-Hong, who calls the new wave of designs exciting but unproven, said the focus should be “getting folks to wear any facial covering that provides a good fit and are comfortable rather than fussing about new devices.”
Advertisement
