Climate change has a cow and worm problem
Scientists spotted a troubling feedback loop
Oct  7, 2020, 10:30am EDT
Share this story
Cattle graze on a dry meadow at a livestock farm, on August 5, 2020, in northwestern France as a heatwave is forecast for the coming days.
Photo by JEAN-FRANCOIS MONIER/AFP via Getty Images
Cows with tummy troubles could be a big problem for the climate, a new study finds. That’s because cattle and other livestock with worms and other parasites produce more of the super potent greenhouse gas, methane, than healthy animals. Methane is 28 to 36 times more powerful than carbon dioxide when it comes to heating up the planet.
The amount of methane coming from cattle and other livestock was estimated to grow 20 percent from 2017 to 2050 by the United Nations Food and Agriculture Organization. But when parasitic worm infections are taken into consideration, the increase in methane could jump as high as 82 percent, according to a new paper published today in Trends in Ecology & Evolution.
A dangerous feedback loop
That’s a large discrepancy, especially given how much domesticated livestock is already contributing to climate change. Livestock make up 60 percent of all the mammal biomass on Earth, and livestock industries are responsible for more than 14 percent of human-caused greenhouse gas emissions. (For comparison, aviation only accounts for about two percent of global emissions.)
What’s even more worrying is that there could be a dangerous feedback loop between climate change, parasitic diseases, and higher methane emissions: Animals infected with parasitic worms and bacteria push out more methane over the course of their lives, which accelerates climate change. Parasites that infect livestock can thrive in warmer temperatures, infecting even more animals, and then the vicious cycle continues.
“That could be a really interesting phenomenon, or an important one that we’re not really considering,” says Vanessa Ezenwa, lead author of the paper and professor of ecology at the University of Georgia.
Infected or not, cows and other hoofed herbivores, called ruminants, are at the top of the methane-emitting heap. Other animals (including people) emit methane, too, but ruminants burp out more of the gas because of their four-chambered stomachs . They have an entire chamber for fermenting food, where microbes that help them digest tough foods pump out a lot of planet-heating gasses. “It’s magnified for them, compared to us,” Ezenwa says.
Parasitic infections can lead to a number of changes that could increase methane emissions from livestock. The animals grow more slowly, which leads to more lifetime emissions since it takes longer for them to develop enough to slaughter for meat. An infection can also reduce milk production, making dairy farming less efficient. Ranchers might decide to cull and replace their cattle more frequently, and evidence suggests that this usually leads to more animals (and more emissions) rather than less.
If every animal caught worms, methane emissions from livestock would rise by 52 percent globally
At the extreme end of the scenarios offered in the paper, if every animal got sick, methane emissions from livestock would rise by 52 percent globally, according to the study authors. To calculate this, Ezenwa and her colleagues reviewed existing research on the effects of parasitic infections on methane production in specific animals. They used those findings to figure out what the potential global impact is on methane emissions. Data from the UN Food and Agriculture Organization served as a baseline.
There are some limitations to the study, which provides estimates rather than hard figures. The researchers used a sliding scale of potential infection prevalence since they didn’t have an actual global rate for parasitic infections. The real-world numbers can vary dramatically from region to region and there are gaps in data.
The results of the new study aren’t necessarily surprising, according to Ermias Kebreab, director of the World Food Center at the University of California, Davis. Kebreab was not involved in the study. “It is common sense,” he says.
“Common sense”
The research might be most helpful in low to middle-income countries where parasitic infections are more common, Kebraeb points out. North America and Europe have boosted the productivity of livestock by better controlling pathogens, he says.
“This is a good article to help us remember that there’s a compounding issue,” Kebraeb says.
Parasitic worms that cause problems for cows develop outside before infecting a host. Some of these worms need warmer temperatures to thrive, according to Ezenwa. As climate change makes winters milder and summers longer in some regions, these parasites have more time to develop and infect livestock, she says.
Ultimately, the new study shows the need for more research to inform efforts to tackle the climate crisis. That could have a string of benefits: healthier animals and a healthier world for all of us to live in.
Next Up In Science
