By Syeda Khaula Saad
Feb. 27, 2020
If you've ever used a filter in your Instagram Story to predict what your 2020 will look like or what Starbucks drink you are , then you're familiar with the app's popular AR effects. What you might not have realized, however, is that you have the ability to create your very own quirky effects to share with the world. Bustle chatted with two creators about how to make Spark AR effects on Instagram and no, you don't need years of experience.
The Spark AR Studio , created by Instagram's parent company Facebook, allows any user to design and create augmented reality (AR) filters and effects to use and share on Instagram Stories. It sounds like an intimidating process, but the people who have actually done it promise that with a little patience, practice, and guidance, it's doable.
Tolmeia (Tolly) Gregory , an ethical and sustainable fashion activist who raises awareness with her Climate Action 101 effect, tells Bustle that she joined Spark AR Studio without knowing much about it at first. "Everything I do online has been self-taught," she says. "So [my filter came from] just playing around online and taking guidance and advice from other filter creators who put out tutorials and information."
If you're ready to take the leap and start playing around with Spark AR Studio like Tolly did, first you have to download it. After you start a new project, you'll see a scene panel where you can add objects that will essentially make up your filter â these objects include the Plane Tracker (for detecting objects) or the Face Tracker (for detecting faces and facial features). From there, you can add different Assets to create designs, masks, or other effects. For example, if you have a rectangle and add a colored overlay to it, that overlay would be an Asset.
Then, position everything the way you want it, add different layers, and preview what your effect would look like in the Simulator . Finally, use Spark AR's Patch Editor to contribute texture, animation, and more to your effects. For instance, if your AR filter puts glasses on someone's face, the glasses and their designs would be the texture. Animations, on the other hand , can be either 2D or 3D. If you've seen filters with confetti or sparkles falling, that's a 2D animation, while things like the dancing Baby Yoda are 3D ones.
That was obviously a simplified tutorial, and even then, it sounds complicated. Ommy Akhe , who started off in information security and is now a creative developer focused on AR , suggests approaching the process like you would Legos. In other words, experiment with different effects and see what fits best. And don't forget to ask the community for help when you need it â according to both Gregory and Akhe, your peers on the platform can be lifesavers. "There's a whole wealth of information and people belonging to the community that can take part in helping you realize your ideas," Akhe tells Bustle.
On top of putting out tutorials on how to modify the color and speed of animations , people also post questions about moving objects around and getting your effect approved for publication . Generally, someone in the community responds to those questions with helpful tips.
Because you probably want every Instagram AR effect to be different, your best bet is to look for inspiration in other creators, ask them questions, and then apply their lessons and tutorials to your own creative vision. Though it might take some time, you'll be on your way to becoming a Spark AR effect designer yourself.
SEARCH
