Louise Glück Is Awarded Nobel Prize in Literature
The American writer was lauded “for her unmistakable poetic voice.”
Louise Glück is the 2020 recipient of the Nobel Prize in Literature. Credit...Katherine Wolkoff
By Alexandra Alter and Alex Marshall
Published Oct. 8, 2020Updated Oct. 9, 2020
The Nobel Prize in Literature was awarded on Thursday to Louise Glück , one of America’s most celebrated poets, for writing “that with austere beauty makes individual existence universal.”
The award was announced at a news conference in Stockholm.
Glück, whose name rhymes with the word “click,” has written numerous poetry collections, many of which deal with the challenges of family life and growing older. They include “The Wild Iris,” for which she won a Pulitzer Prize in 1993, and “ Faithful and Virtuous Night ,” about mortality and grief, from 2014. She was named the United States’ poet laureate in 2003.
At the Nobel announcement, Anders Olsson, the chair of the prize-giving committee, praised her minimalist voice and especially poems that get to the heart of family life.
“Louise Glück’s voice is unmistakable,” he said. “It is candid and uncompromising, and it signals this poet wants to be understood.” But he also said her voice was also “full of humor and biting wit.”
Reached at her home in Cambridge, Mass., on Thursday morning, Glück said she was “completely flabbergasted that they would choose a white American lyric poet.”
She was stunned, she said in the interview , to receive the award when so many other exceptional American poets and writers have been overlooked. “When you think of the American poets who have not gotten the Nobel, it’s daunting,” she said. “I was shocked.”
Born in New York City in 1943, Glück grew up on Long Island and from an early age was drawn to reading and writing poetry. Her parents read her classical mythology as bedtime stories, and she was transfixed by the tales of Greek gods and heroes — themes she would later explore in her work. She wrote some of her earliest verses when she was 5, and set her mind to becoming a poet when she was in her early teens. She struggled with anorexia as a teenager, a disease she later attributed to her obsession with purity and achieving control, and almost starved herself to death before eventually recovering through therapy.
She began taking poetry workshops around that time, and attended Sarah Lawrence College and later Columbia University, where she studied with the poet Stanley Kunitz. She supported herself by working as a secretary so that she could write on the side. In 1968, she published her first collection, “Firstborn.” While her debut was well received by critics, she wrestled with writers’ block afterward and took a teaching position at Goddard College in Vermont. Working with students inspired her to start writing again, and she went on to publish a dozen volumes of poetry.
The 2020 Nobel Prizes
See all of the 2020 winners here.
Drs. Harvey J. Alter, Michael Houghton and Charles M. Rice received the prize for medicine for their discovery of the hepatitis C virus .
Roger Penrose, Reinhard Genzel and Andrea Ghez received the physics prize for their discoveries that have improved understanding of the universe, including work on black holes .
Emmanuelle Charpentier and Jennifer A. Doudna were awarded the chemistry prize for their work on genome editing.
This year’s Peace Prize was awarded to the U.N.’s World Food Program .
Two U.S. economists, Paul R. Milgrom and Robert B. Wilson, were awarded the Nobel in economic science for their work on auction theory.
In much of her work, Glück draws inspiration from mythological figures. In her 1996 collection, “Meadowlands,” she weaves together the figures of Odysseus and Penelope from Homer’s Odyssey with the story of the dissolution of a modern-day marriage. In her 2006 collection, “Averno,” she used the myth of Persephone as a lens to mother-daughter relationships, suffering, aging and death.
Glück’s verses often reflect her preoccupation with dark themes — isolation, betrayal, fractured family and marital relationships, death. But her spare, distilled language, and her frequent recourse to familiar mythological figures, gives her poetry a universal and timeless feel, said the critic and writer Daniel Mendelsohn, the editor at large for The New York Review of Books.
“When you read her poems about these difficult things, you feel cleansed rather than depressed,” he said. “This is one of the purest poetic sensibilities in world literature right now. It’s a kind of absolute poetry, poetry with no gimmicks, no pandering to fads or trends. It has the quality of something standing almost as outside of time.”
In an interview in 2012, Glück described writing as “a torment, a place of suffering, harrowing.” Rather than a means of self exploration, she views poetry as a way to extract meaning from loss and pain.
Throughout her career, Glück has returned to familiar themes but has experimented with new poetic forms. “I think you have always to be surprised and to be in a way a beginner again,” she said on Thursday. “Otherwise I would bore myself to tears.”
Her sentences are often spare and pared down and sculpted, and can feel almost oracular at times, conversational at others.
“Like many great poets, she is always reforming herself,” said Jonathan Galassi, president of Farrar, Straus & Giroux, who has edited Glück since 2006. “Once she finished something, it’s sort of dead to her, and she has to start over again.”
This summer, Glück finished work on a new poetry collection, titled “Winter Recipes From the Collective,” which explores the indignities and the surreal comedy of aging and mortality, and will be released by FSG next year.
Literary critics and fellow poets have long admired her intensely distilled language and her unflinching self-examination.
“Her poems are flash bulletins from her inner life, a region that she examines unsparingly,” the poet Dan Chiasson wrote in The New Yorker .
William Logan, in a 2009 Times review of “A Village Life,” called Glück “perhaps the most popular literary poet in America.” Her audience may not be as large as others’, he wrote, but “part of her cachet is that her poems are like secret messages for the initiated.”
Glück herself has expressed discomfort with the notion of her poetry as popular.
“When I’m told I have a large readership, I think, ‘Oh great, I’m going to turn out to be Longfellow : somebody easy to understand, easy to like, the kind of diluted experience available to many. And I don’t want to be Longfellow,” she said in a 2009 interview with American Poet, the journal of the Academy of American Poets.
Glück is the first female poet to be awarded the prize since Wislawa Szymborska, a Polish writer, in 1996 . Other poets to have received the award include Seamus Heaney, the Northern Irish poet, who won in 1995 . She is the first American to win since Bob Dylan in 2016.
She will give her Nobel lecture in the United States because of coronavirus travel restrictions, said Mats Malm, the permanent secretary of the Swedish Academy, which awards the prize.
Many in the book world celebrated the academy’s selection of Glück as a worthy choice made based on purely literary merits. It marks a much-needed reset for the academy and for the literature award, which has been plagued by controversies and scandals in recent years.
Last year, the academy was criticized after it awarded the prize to Peter Handke , an Austrian author and playwright who has been accused of genocide denial for questioning events during the Balkan Wars of the 1990s — including the Srebrenica massacre, in which about 8,000 Muslim men and boys were murdered.
That furor over the award came a year after the academy postponed the 2018 prize because of a scandal involving the husband of an academy member who was accused of sexual misconduct and of leaking information to bookmakers. That man, Jean-Claude Arnault, was later sentenced to two years in prison for rape .
Those events were a low point for the prize, which dates to 1901 and has been awarded to some of the world’s most influential and revered novelists, poets and playwrights. Prominent past laureates include Toni Morrison , Kazuo Ishiguro , Alice Munro , Gabriel García Márquez , Saul Bellow and Albert Camus . In 1964, the academy chose Jean-Paul Sartre, who refused the honor , saying that writers should not accept awards.
Given the recent controversies, many observers expected this year’s award to go to an uncontroversial choice. “The Swedish Academy knows they can’t afford another scandal,” Bjorn Wiman, the culture editor of the Swedish newspaper Dagens Nyheter, said in a telephone interview before the announcement.
But an adviser to the prize-giving committee denied this in an email on Wednesday. “We haven’t focused on making a ‘safe’ pick or discussed the choice in such terms,” said Rebecka Karde, a journalist and one of three external experts who helped choose this year’s winner. “It’s all about the quality of the output of the writer who gets it.”
The Nobel Prize in Literature, which is given for a writer’s entire body of work and is regarded as perhaps the world’s most prestigious literary award, comes with a prize of 10 million Swedish krona, or about $1.1 million.
For Glück, who has always had a complicated relationship to literary renown, winning the Nobel felt like a long shot, and she found herself unsettled by the news on Thursday.
“I thought my chances were very poor, and that was fine, because I treasure my daily life and my friendships, and I didn’t want my friendships complicated, and I didn’t want my daily life sacrificed,” she said. “But there’s also a kind of covetousness. You want your work honored. Everyone does.”
Who else won a Nobel Prize this year?
Harvey J. Alter, Michael Houghton and Charles M. Rice received the Nobel Prize in Physiology or Medicine on Monday for the discovery of the hepatitis C virus, a breakthrough that “made possible blood tests and new medicines that have saved millions of lives,” the Nobel committee said.
Emmanuelle Charpentier and Jennifer A. Doudna were awarded the Nobel Prize in Chemistry on Wednesday for their 2012 work on the development of Crispr-Cas9, a method for genome editing.
When will the remaining Nobel Prizes be announced?
The Peace Prize will be announced on Friday. Read about last year’s winner, Prime Minister Abiy Ahmed of Ethiopia .
The Nobel Memorial Prize in Economic Science will be announced on Monday in Sweden. Read about last year’s winners, Abhijit Banerjee, Esther Duflo and Michael Kremer .
Advertisement
